__title__ = 'pi'
__description__ = 'pi - Client for the CrunchDAO Pi Project!'
__version__ = '0.1.1'
__author__ = 'Enzo CACERES'
__author_email__ = 'enzo.caceres@crunchdao.com'
__url__ = 'https://github.com/crunchdao/pi-client'
